#!/bin/bash

target_branch=$1
current_branch=$(git rev-parse --abbrev-ref HEAD)

echo $current_branch

if test $# -eq 0; then
  exit 1
fi

git checkout $target_branch
git pull
git checkout $current_branch

exit 0