#!/bin/bash

google-chrome https://web.whatsapp.com/ https://www.meucontroledeponto.com.br/day_records https://clockify.me/tracker https://app.slack.com/client/T065VA43V/GQK57JSLA https://teams.microsoft.com/ https://trello.com/lucasrodriguespessone/boards https://zanderlan-n.github.io/prManager/
